### ISSUE TITLE
[S2-07] forget password

### ISSUE THREAD

**Issue by TranTLy** [LMN-Team/itedu-website-frontend#10]

**Comment by TranTLy** [comment]
Hi @duyminh256 , nhờ ông xem lại giúp t 4 phần này nha. Thanks
1. Sử dụng class name được cấu hình trong file **`global.style.scss`** (file này mới được update trên nhánh dev-master) để chỉnh css cho message thông báo giống với common.
VD: `<div className = "message success"> Thông báo </div>`

Hình 1.1:
![image](https://user-images.githubusercontent.com/25228809/69611898-53155300-1061-11ea-9077-fd9f2c3a564b.png)

Hình 1.2:
![image](https://user-images.githubusercontent.com/25228809/69612947-48f45400-1063-11ea-8b4c-49986d2db28f.png)


2. File `ResetPasswordPage.component.jsx`: Dòng 17 và 19 có thể gộp lại thành 1 dòng

Hình 2:
![image](https://user-images.githubusercontent.com/25228809/69612242-e2bb0180-1061-11ea-85c7-71705be7b044.png)

3. Cần thêm comment chú thích cho 2 component: `VerifiedTokenResultPage.component`, `ResetPasswordResultPage.component`

4. S2-07 bao gồm cả phần **`ChangePasswordPage`** (phần này D. Minh chưa làm)

**Note**:
- Chưa test `VerifiedTokenResultPage` (do còn lỗi)

**Comment by duyminh256** [comment]
Feedback:
4. S2-07 tui chỉ xử lý phần reset password thôi nha còn phần changePasswordPage thì luồng sẽ đi từ khi user đăng nhập -> xem thông tin -> chỉnh sửa thông tin hoặc  mới tới chỉnh sửa password, ở spint này mình chỉ tới đăng nhập được thôi. Nếu muốn thì sẽ note làm ở sprint sau

Những phần còn lại sẽ được sửa cho phù hợp, nếu chức năng không bị lỗi thì tui sẽ clean lại code

**Comment by TranTLy** [comment]
Ok, thanks ông

**Comment by duyminh256** [comment]
Đã sửa chữa. @TranTLy bà nghĩ sao về ý kiến thông báo success màu xanh lá cây?

**Comment by duyminh256** [comment]
Đã chỉnh sửa lỗi @TranTLy . Change route cho đồng bộ @nhoknguyen00

**Comment by TranTLy** [comment]
success xanh lá cây hợp lý hơn màu hiện tại, t sẽ sửa, thanks ông
